spring:
  application:
    name: papercheck
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your_ip/your_database?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: your_name
    password: your_password

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: MYSQL
