spring:
  application:
    name: stms
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.174.7/stms_db?allowMultiQueries=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: stms_user
    password: PSWpsw123456.
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  server:
    tomcat:
      uri-encoding: UTF-8

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: MYSQL
mybatis:
  mapperLocations: classpath:mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true